services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php_daliapp:
        build: .docker/php
        container_name: php_daliapp
        restart: unless-stopped
        tty: true
        ports:
            # - 80:80
            - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - mysql_net

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx_daliapp:
        image: nginx
        container_name: nginx_daliapp
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php_daliapp
            # - mysql_daliapp
        networks:
            - mysql_net
    # ####################################################################################################
    # # DATABASE (MySQL)
    # ####################################################################################################
    # mysql_daliapp:
    #     image: mysql/mysql-server:8.0
    #     container_name: mysql_db_daliapp
    #     restart: unless-stopped
    #     tty: true
    #     ports:
    #         - 33306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel
    #         MYSQL_USER: sail
    #         MYSQL_PASSWORD: password
    #     networks:
    #         - mysql_net

    # ####################################################################################################
    # # phpMyAdmin
    # ####################################################################################################
    # phpmyadmin_daliapp:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: phpmyadmin_db_daliapp
    #     restart: unless-stopped
    #     tty: true
    #     ports:
    #         - 8080:80
    #     links:
    #         - mysql_daliapp
    #     environment:
    #         PMA_HOST: mysql_daliapp
    #         PMA_PORT: 3306
    #         PMA_ARBITRARY: 1
    #     volumes:
    #         - .docker/phpmyadmin/sessions:/sessions
    #     networks:
    #         - mysql_net

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail_daliapp:
        image: axllent/mailpit:latest
        container_name: mail_daliapp
        restart: unless-stopped
        tty: true
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - mysql_net

networks:
    mysql_net:
        external: true
        driver: bridge